// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xexecutefirstlayer.h"

extern XExecutefirstlayer_Config XExecutefirstlayer_ConfigTable[];

XExecutefirstlayer_Config *XExecutefirstlayer_LookupConfig(u16 DeviceId) {
	XExecutefirstlayer_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEXECUTEFIRSTLAYER_NUM_INSTANCES; Index++) {
		if (XExecutefirstlayer_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XExecutefirstlayer_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XExecutefirstlayer_Initialize(XExecutefirstlayer *InstancePtr, u16 DeviceId) {
	XExecutefirstlayer_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XExecutefirstlayer_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XExecutefirstlayer_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

