:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2016.4
:: Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado_HLS/2016.4/../../Vivado/2016.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z045ffg900-2 ../xilinx_com_hls_executeFirstLayer1_p2_1_0.zip
