// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xexecutefirstlayer.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XExecutefirstlayer_CfgInitialize(XExecutefirstlayer *InstancePtr, XExecutefirstlayer_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XExecutefirstlayer_Start(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_AP_CTRL) & 0x80;
    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XExecutefirstlayer_IsDone(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XExecutefirstlayer_IsIdle(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XExecutefirstlayer_IsReady(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XExecutefirstlayer_EnableAutoRestart(XExecutefirstlayer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XExecutefirstlayer_DisableAutoRestart(XExecutefirstlayer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_AP_CTRL, 0);
}

void XExecutefirstlayer_Set_group_id_x(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GROUP_ID_X_DATA, Data);
}

u32 XExecutefirstlayer_Get_group_id_x(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GROUP_ID_X_DATA);
    return Data;
}

void XExecutefirstlayer_Set_group_id_y(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GROUP_ID_Y_DATA, Data);
}

u32 XExecutefirstlayer_Get_group_id_y(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GROUP_ID_Y_DATA);
    return Data;
}

void XExecutefirstlayer_Set_group_id_z(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GROUP_ID_Z_DATA, Data);
}

u32 XExecutefirstlayer_Get_group_id_z(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GROUP_ID_Z_DATA);
    return Data;
}

void XExecutefirstlayer_Set_bias(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_BIAS_DATA, Data);
}

u32 XExecutefirstlayer_Get_bias(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_BIAS_DATA);
    return Data;
}

void XExecutefirstlayer_Set_Layer1_Neurons_GPU(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_LAYER1_NEURONS_GPU_DATA, Data);
}

u32 XExecutefirstlayer_Get_Layer1_Neurons_GPU(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_LAYER1_NEURONS_GPU_DATA);
    return Data;
}

void XExecutefirstlayer_Set_Layer1_Weights_GPU(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_LAYER1_WEIGHTS_GPU_DATA, Data);
}

u32 XExecutefirstlayer_Get_Layer1_Weights_GPU(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_LAYER1_WEIGHTS_GPU_DATA);
    return Data;
}

void XExecutefirstlayer_Set_Layer2_Neurons_GPU(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_LAYER2_NEURONS_GPU_DATA, Data);
}

u32 XExecutefirstlayer_Get_Layer2_Neurons_GPU(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_LAYER2_NEURONS_GPU_DATA);
    return Data;
}

void XExecutefirstlayer_Set_r_offset(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_R_OFFSET_DATA, Data);
}

u32 XExecutefirstlayer_Get_r_offset(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_R_OFFSET_DATA);
    return Data;
}

void XExecutefirstlayer_Set_c_offset(XExecutefirstlayer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_C_OFFSET_DATA, Data);
}

u32 XExecutefirstlayer_Get_c_offset(XExecutefirstlayer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_C_OFFSET_DATA);
    return Data;
}

void XExecutefirstlayer_InterruptGlobalEnable(XExecutefirstlayer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GIE, 1);
}

void XExecutefirstlayer_InterruptGlobalDisable(XExecutefirstlayer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_GIE, 0);
}

void XExecutefirstlayer_InterruptEnable(XExecutefirstlayer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_IER);
    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_IER, Register | Mask);
}

void XExecutefirstlayer_InterruptDisable(XExecutefirstlayer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_IER);
    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_IER, Register & (~Mask));
}

void XExecutefirstlayer_InterruptClear(XExecutefirstlayer *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_ISR, Mask);
}

u32 XExecutefirstlayer_InterruptGetEnabled(XExecutefirstlayer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_IER);
}

u32 XExecutefirstlayer_InterruptGetStatus(XExecutefirstlayer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XExecutefirstlayer_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER_CONTROL_ADDR_ISR);
}

