// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XEXECUTEFIRSTLAYER_H
#define XEXECUTEFIRSTLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xexecutefirstlayer_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XExecutefirstlayer_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XExecutefirstlayer;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XExecutefirstlayer_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XExecutefirstlayer_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XExecutefirstlayer_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XExecutefirstlayer_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XExecutefirstlayer_Initialize(XExecutefirstlayer *InstancePtr, u16 DeviceId);
XExecutefirstlayer_Config* XExecutefirstlayer_LookupConfig(u16 DeviceId);
int XExecutefirstlayer_CfgInitialize(XExecutefirstlayer *InstancePtr, XExecutefirstlayer_Config *ConfigPtr);
#else
int XExecutefirstlayer_Initialize(XExecutefirstlayer *InstancePtr, const char* InstanceName);
int XExecutefirstlayer_Release(XExecutefirstlayer *InstancePtr);
#endif

void XExecutefirstlayer_Start(XExecutefirstlayer *InstancePtr);
u32 XExecutefirstlayer_IsDone(XExecutefirstlayer *InstancePtr);
u32 XExecutefirstlayer_IsIdle(XExecutefirstlayer *InstancePtr);
u32 XExecutefirstlayer_IsReady(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_EnableAutoRestart(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_DisableAutoRestart(XExecutefirstlayer *InstancePtr);

void XExecutefirstlayer_Set_group_id_x(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_group_id_x(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_group_id_y(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_group_id_y(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_group_id_z(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_group_id_z(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_bias(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_bias(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_Layer1_Neurons_GPU(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_Layer1_Neurons_GPU(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_Layer1_Weights_GPU(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_Layer1_Weights_GPU(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_Layer2_Neurons_GPU(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_Layer2_Neurons_GPU(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_r_offset(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_r_offset(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_Set_c_offset(XExecutefirstlayer *InstancePtr, u32 Data);
u32 XExecutefirstlayer_Get_c_offset(XExecutefirstlayer *InstancePtr);

void XExecutefirstlayer_InterruptGlobalEnable(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_InterruptGlobalDisable(XExecutefirstlayer *InstancePtr);
void XExecutefirstlayer_InterruptEnable(XExecutefirstlayer *InstancePtr, u32 Mask);
void XExecutefirstlayer_InterruptDisable(XExecutefirstlayer *InstancePtr, u32 Mask);
void XExecutefirstlayer_InterruptClear(XExecutefirstlayer *InstancePtr, u32 Mask);
u32 XExecutefirstlayer_InterruptGetEnabled(XExecutefirstlayer *InstancePtr);
u32 XExecutefirstlayer_InterruptGetStatus(XExecutefirstlayer *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
