// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xexecutefirstlayer1_p3.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XExecutefirstlayer1_p3_CfgInitialize(XExecutefirstlayer1_p3 *InstancePtr, XExecutefirstlayer1_p3_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XExecutefirstlayer1_p3_Start(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_AP_CTRL) & 0x80;
    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XExecutefirstlayer1_p3_IsDone(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XExecutefirstlayer1_p3_IsIdle(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XExecutefirstlayer1_p3_IsReady(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XExecutefirstlayer1_p3_EnableAutoRestart(XExecutefirstlayer1_p3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XExecutefirstlayer1_p3_DisableAutoRestart(XExecutefirstlayer1_p3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_AP_CTRL, 0);
}

void XExecutefirstlayer1_p3_Set_group_id_x(XExecutefirstlayer1_p3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GROUP_ID_X_DATA, Data);
}

u32 XExecutefirstlayer1_p3_Get_group_id_x(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GROUP_ID_X_DATA);
    return Data;
}

void XExecutefirstlayer1_p3_Set_group_id_y(XExecutefirstlayer1_p3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GROUP_ID_Y_DATA, Data);
}

u32 XExecutefirstlayer1_p3_Get_group_id_y(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GROUP_ID_Y_DATA);
    return Data;
}

void XExecutefirstlayer1_p3_Set_group_id_z(XExecutefirstlayer1_p3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GROUP_ID_Z_DATA, Data);
}

u32 XExecutefirstlayer1_p3_Get_group_id_z(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GROUP_ID_Z_DATA);
    return Data;
}

void XExecutefirstlayer1_p3_Set_bias(XExecutefirstlayer1_p3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_BIAS_DATA, Data);
}

u32 XExecutefirstlayer1_p3_Get_bias(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_BIAS_DATA);
    return Data;
}

void XExecutefirstlayer1_p3_Set_Layer1_Neurons_GPU(XExecutefirstlayer1_p3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_LAYER1_NEURONS_GPU_DATA, Data);
}

u32 XExecutefirstlayer1_p3_Get_Layer1_Neurons_GPU(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_LAYER1_NEURONS_GPU_DATA);
    return Data;
}

void XExecutefirstlayer1_p3_Set_Layer1_Weights_GPU(XExecutefirstlayer1_p3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_LAYER1_WEIGHTS_GPU_DATA, Data);
}

u32 XExecutefirstlayer1_p3_Get_Layer1_Weights_GPU(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_LAYER1_WEIGHTS_GPU_DATA);
    return Data;
}

void XExecutefirstlayer1_p3_Set_Layer2_Neurons_GPU(XExecutefirstlayer1_p3 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_LAYER2_NEURONS_GPU_DATA, Data);
}

u32 XExecutefirstlayer1_p3_Get_Layer2_Neurons_GPU(XExecutefirstlayer1_p3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_LAYER2_NEURONS_GPU_DATA);
    return Data;
}

void XExecutefirstlayer1_p3_InterruptGlobalEnable(XExecutefirstlayer1_p3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GIE, 1);
}

void XExecutefirstlayer1_p3_InterruptGlobalDisable(XExecutefirstlayer1_p3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_GIE, 0);
}

void XExecutefirstlayer1_p3_InterruptEnable(XExecutefirstlayer1_p3 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_IER);
    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_IER, Register | Mask);
}

void XExecutefirstlayer1_p3_InterruptDisable(XExecutefirstlayer1_p3 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_IER);
    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_IER, Register & (~Mask));
}

void XExecutefirstlayer1_p3_InterruptClear(XExecutefirstlayer1_p3 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XExecutefirstlayer1_p3_WriteReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_ISR, Mask);
}

u32 XExecutefirstlayer1_p3_InterruptGetEnabled(XExecutefirstlayer1_p3 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_IER);
}

u32 XExecutefirstlayer1_p3_InterruptGetStatus(XExecutefirstlayer1_p3 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XExecutefirstlayer1_p3_ReadReg(InstancePtr->Control_BaseAddress, XEXECUTEFIRSTLAYER1_P3_CONTROL_ADDR_ISR);
}

