// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xexecutefirstlayer1_p4.h"

extern XExecutefirstlayer1_p4_Config XExecutefirstlayer1_p4_ConfigTable[];

XExecutefirstlayer1_p4_Config *XExecutefirstlayer1_p4_LookupConfig(u16 DeviceId) {
	XExecutefirstlayer1_p4_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEXECUTEFIRSTLAYER1_P4_NUM_INSTANCES; Index++) {
		if (XExecutefirstlayer1_p4_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XExecutefirstlayer1_p4_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XExecutefirstlayer1_p4_Initialize(XExecutefirstlayer1_p4 *InstancePtr, u16 DeviceId) {
	XExecutefirstlayer1_p4_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XExecutefirstlayer1_p4_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XExecutefirstlayer1_p4_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

